# Generated by Django 4.2 on 2024-05-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=None, verbose_name='Адрес ссылки'),
        ),
        migrations.AddField(
            model_name='listbooks',
            name='slug',
            field=models.SlugField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='boss',
            field=models.CharField(max_length=100, verbose_name='Начальник архива'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='senior_archivist',
            field=models.CharField(max_length=100, verbose_name='Старший архивист'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type_link',
            field=models.CharField(max_length=250, verbose_name='Тип ссылки'),
        ),
        migrations.AlterField(
            model_name='listbooks',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='listbooks',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='listbooks',
            name='numb',
            field=models.IntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='listbooks',
            name='publishing',
            field=models.CharField(max_length=255, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='end_time_lunch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='end_time_morning',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Начало обеда'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='name_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='start_time_lunch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Конец обеда'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='start_time_morning',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='operatingmode',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='archive', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('main_them', 'Основной пост на главной'), ('about_archive', 'Об архиве'), ('news', 'Новости'), ('article', 'Статьи'), ('exhibitions', 'Выставки'), ('reading_room', 'Читальный зал'), ('requests_ls', 'запросы л/с'), ('requests_sp', 'запросы соц. пр.')], max_length=100, verbose_name='Тип поста'),
        ),
    ]
