# Generated by Django 4.2 on 2024-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_link_url_listbooks_slug_alter_contacts_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('main_them', 'Основной пост на главной'), ('about_archive', 'Об архиве'), ('news', 'Новости'), ('article', 'Статьи'), ('exhibitions', 'Выставки'), ('reading_room', 'Читальный зал'), ('requests_ls', 'запросы л/с'), ('requests_sp', 'запросы соц. пр.'), ('external_reference', 'внешние ссылки')], max_length=100, verbose_name='Тип поста'),
        ),
    ]
