# Generated by Django 4.2 on 2024-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_remove_post_image_imageforpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageforpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='archive', verbose_name='Изображение'),
        ),
    ]
