# Generated by Django 4.2 on 2024-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_post_text_link_alter_post_link_alter_post_type_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст ссылки'),
        ),
    ]
